# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_cron_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='estafette/ci/manifest/v1/estafette_cron_event.proto',
  package='estafette.ci.manifest.v1',
  syntax='proto3',
  serialized_options=_b('\n\034com.estafette.ci.manifest.v1P\001Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\252\002\030Estafette.Ci.Manifest.V1'),
  serialized_pb=_b('\n3estafette/ci/manifest/v1/estafette_cron_event.proto\x12\x18\x65stafette.ci.manifest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\">\n\x12\x45stafetteCronEvent\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampBx\n\x1c\x63om.estafette.ci.manifest.v1P\x01Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\xaa\x02\x18\x45stafette.Ci.Manifest.V1b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ESTAFETTECRONEVENT = _descriptor.Descriptor(
  name='EstafetteCronEvent',
  full_name='estafette.ci.manifest.v1.EstafetteCronEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='estafette.ci.manifest.v1.EstafetteCronEvent.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=176,
)

_ESTAFETTECRONEVENT.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['EstafetteCronEvent'] = _ESTAFETTECRONEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstafetteCronEvent = _reflection.GeneratedProtocolMessageType('EstafetteCronEvent', (_message.Message,), dict(
  DESCRIPTOR = _ESTAFETTECRONEVENT,
  __module__ = 'estafette.ci.manifest.v1.estafette_cron_event_pb2'
  # @@protoc_insertion_point(class_scope:estafette.ci.manifest.v1.EstafetteCronEvent)
  ))
_sym_db.RegisterMessage(EstafetteCronEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
