# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_semver_version.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from estafette.ci.manifest.v1 import string_or_string_array_pb2 as estafette_dot_ci_dot_manifest_dot_v1_dot_string__or__string__array__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='estafette/ci/manifest/v1/estafette_semver_version.proto',
  package='estafette.ci.manifest.v1',
  syntax='proto3',
  serialized_options=_b('\n\034com.estafette.ci.manifest.v1P\001Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\252\002\030Estafette.Ci.Manifest.V1'),
  serialized_pb=_b('\n7estafette/ci/manifest/v1/estafette_semver_version.proto\x12\x18\x65stafette.ci.manifest.v1\x1a\x35\x65stafette/ci/manifest/v1/string_or_string_array.proto\"\xa4\x01\n\x16\x45stafetteSemverVersion\x12\r\n\x05major\x18\x01 \x01(\x03\x12\r\n\x05minor\x18\x02 \x01(\x03\x12\r\n\x05patch\x18\x03 \x01(\t\x12\x16\n\x0elabel_template\x18\x04 \x01(\t\x12\x45\n\x0erelease_branch\x18\x05 \x01(\x0b\x32-.estafette.ci.manifest.v1.StringOrStringArrayBx\n\x1c\x63om.estafette.ci.manifest.v1P\x01Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\xaa\x02\x18\x45stafette.Ci.Manifest.V1b\x06proto3')
  ,
  dependencies=[estafette_dot_ci_dot_manifest_dot_v1_dot_string__or__string__array__pb2.DESCRIPTOR,])




_ESTAFETTESEMVERVERSION = _descriptor.Descriptor(
  name='EstafetteSemverVersion',
  full_name='estafette.ci.manifest.v1.EstafetteSemverVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='estafette.ci.manifest.v1.EstafetteSemverVersion.major', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor', full_name='estafette.ci.manifest.v1.EstafetteSemverVersion.minor', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patch', full_name='estafette.ci.manifest.v1.EstafetteSemverVersion.patch', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_template', full_name='estafette.ci.manifest.v1.EstafetteSemverVersion.label_template', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='release_branch', full_name='estafette.ci.manifest.v1.EstafetteSemverVersion.release_branch', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=305,
)

_ESTAFETTESEMVERVERSION.fields_by_name['release_branch'].message_type = estafette_dot_ci_dot_manifest_dot_v1_dot_string__or__string__array__pb2._STRINGORSTRINGARRAY
DESCRIPTOR.message_types_by_name['EstafetteSemverVersion'] = _ESTAFETTESEMVERVERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstafetteSemverVersion = _reflection.GeneratedProtocolMessageType('EstafetteSemverVersion', (_message.Message,), {
  'DESCRIPTOR' : _ESTAFETTESEMVERVERSION,
  '__module__' : 'estafette.ci.manifest.v1.estafette_semver_version_pb2'
  # @@protoc_insertion_point(class_scope:estafette.ci.manifest.v1.EstafetteSemverVersion)
  })
_sym_db.RegisterMessage(EstafetteSemverVersion)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
