# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from estafette.ci.manifest.v1 import estafette_cron_event_pb2 as estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__cron__event__pb2
from estafette.ci.manifest.v1 import estafette_docker_event_pb2 as estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__docker__event__pb2
from estafette.ci.manifest.v1 import estafette_git_event_pb2 as estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__git__event__pb2
from estafette.ci.manifest.v1 import estafette_manual_event_pb2 as estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__manual__event__pb2
from estafette.ci.manifest.v1 import estafette_pipeline_event_pb2 as estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__pipeline__event__pb2
from estafette.ci.manifest.v1 import estafette_pub_sub_event_pb2 as estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__pub__sub__event__pb2
from estafette.ci.manifest.v1 import estafette_release_event_pb2 as estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__release__event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='estafette/ci/manifest/v1/estafette_event.proto',
  package='estafette.ci.manifest.v1',
  syntax='proto3',
  serialized_options=_b('\n\034com.estafette.ci.manifest.v1P\001Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\252\002\030Estafette.Ci.Manifest.V1'),
  serialized_pb=_b('\n.estafette/ci/manifest/v1/estafette_event.proto\x12\x18\x65stafette.ci.manifest.v1\x1a\x33\x65stafette/ci/manifest/v1/estafette_cron_event.proto\x1a\x35\x65stafette/ci/manifest/v1/estafette_docker_event.proto\x1a\x32\x65stafette/ci/manifest/v1/estafette_git_event.proto\x1a\x35\x65stafette/ci/manifest/v1/estafette_manual_event.proto\x1a\x37\x65stafette/ci/manifest/v1/estafette_pipeline_event.proto\x1a\x36\x65stafette/ci/manifest/v1/estafette_pub_sub_event.proto\x1a\x36\x65stafette/ci/manifest/v1/estafette_release_event.proto\"\xcd\x03\n\x0e\x45stafetteEvent\x12\x42\n\x08pipeline\x18\x01 \x01(\x0b\x32\x30.estafette.ci.manifest.v1.EstafettePipelineEvent\x12@\n\x07release\x18\x02 \x01(\x0b\x32/.estafette.ci.manifest.v1.EstafetteReleaseEvent\x12\x38\n\x03git\x18\x03 \x01(\x0b\x32+.estafette.ci.manifest.v1.EstafetteGitEvent\x12>\n\x06\x64ocker\x18\x04 \x01(\x0b\x32..estafette.ci.manifest.v1.EstafetteDockerEvent\x12:\n\x04\x63ron\x18\x05 \x01(\x0b\x32,.estafette.ci.manifest.v1.EstafetteCronEvent\x12?\n\x07pub_sub\x18\x06 \x01(\x0b\x32..estafette.ci.manifest.v1.EstafettePubSubEvent\x12>\n\x06manual\x18\x07 \x01(\x0b\x32..estafette.ci.manifest.v1.EstafetteManualEventBx\n\x1c\x63om.estafette.ci.manifest.v1P\x01Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\xaa\x02\x18\x45stafette.Ci.Manifest.V1b\x06proto3')
  ,
  dependencies=[estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__cron__event__pb2.DESCRIPTOR,estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__docker__event__pb2.DESCRIPTOR,estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__git__event__pb2.DESCRIPTOR,estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__manual__event__pb2.DESCRIPTOR,estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__pipeline__event__pb2.DESCRIPTOR,estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__pub__sub__event__pb2.DESCRIPTOR,estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__release__event__pb2.DESCRIPTOR,])




_ESTAFETTEEVENT = _descriptor.Descriptor(
  name='EstafetteEvent',
  full_name='estafette.ci.manifest.v1.EstafetteEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline', full_name='estafette.ci.manifest.v1.EstafetteEvent.pipeline', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='release', full_name='estafette.ci.manifest.v1.EstafetteEvent.release', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git', full_name='estafette.ci.manifest.v1.EstafetteEvent.git', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='docker', full_name='estafette.ci.manifest.v1.EstafetteEvent.docker', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cron', full_name='estafette.ci.manifest.v1.EstafetteEvent.cron', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pub_sub', full_name='estafette.ci.manifest.v1.EstafetteEvent.pub_sub', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manual', full_name='estafette.ci.manifest.v1.EstafetteEvent.manual', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=922,
)

_ESTAFETTEEVENT.fields_by_name['pipeline'].message_type = estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__pipeline__event__pb2._ESTAFETTEPIPELINEEVENT
_ESTAFETTEEVENT.fields_by_name['release'].message_type = estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__release__event__pb2._ESTAFETTERELEASEEVENT
_ESTAFETTEEVENT.fields_by_name['git'].message_type = estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__git__event__pb2._ESTAFETTEGITEVENT
_ESTAFETTEEVENT.fields_by_name['docker'].message_type = estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__docker__event__pb2._ESTAFETTEDOCKEREVENT
_ESTAFETTEEVENT.fields_by_name['cron'].message_type = estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__cron__event__pb2._ESTAFETTECRONEVENT
_ESTAFETTEEVENT.fields_by_name['pub_sub'].message_type = estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__pub__sub__event__pb2._ESTAFETTEPUBSUBEVENT
_ESTAFETTEEVENT.fields_by_name['manual'].message_type = estafette_dot_ci_dot_manifest_dot_v1_dot_estafette__manual__event__pb2._ESTAFETTEMANUALEVENT
DESCRIPTOR.message_types_by_name['EstafetteEvent'] = _ESTAFETTEEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstafetteEvent = _reflection.GeneratedProtocolMessageType('EstafetteEvent', (_message.Message,), dict(
  DESCRIPTOR = _ESTAFETTEEVENT,
  __module__ = 'estafette.ci.manifest.v1.estafette_event_pb2'
  # @@protoc_insertion_point(class_scope:estafette.ci.manifest.v1.EstafetteEvent)
  ))
_sym_db.RegisterMessage(EstafetteEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
