# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.v1/estafette_stage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='manifest.v1/estafette_stage.proto',
  package='manifest.v1',
  syntax='proto3',
  serialized_options=_b('\n\"io.estafette.ci.protos.manifest.v1Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\252\002\030Estafette.CI.Manifest.V1'),
  serialized_pb=_b('\n!manifest.v1/estafette_stage.proto\x12\x0bmanifest.v1\x1a\x19google/protobuf/any.proto\"\xb2\x03\n\x0e\x45stafetteStage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0f\x63ontainer_image\x18\x02 \x01(\t\x12\r\n\x05shell\x18\x03 \x01(\t\x12\x19\n\x11working_directory\x18\x04 \x01(\t\x12\x10\n\x08\x63ommands\x18\x05 \x03(\t\x12\x0c\n\x04when\x18\x06 \x01(\t\x12:\n\x08\x65nv_vars\x18\x07 \x03(\x0b\x32(.manifest.v1.EstafetteStage.EnvVarsEntry\x12\x15\n\rauto_injected\x18\x08 \x01(\x08\x12\x0f\n\x07retries\x18\t \x01(\x03\x12L\n\x11\x63ustom_properties\x18\n \x03(\x0b\x32\x31.manifest.v1.EstafetteStage.CustomPropertiesEntry\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1aM\n\x15\x43ustomPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x42|\n\"io.estafette.ci.protos.manifest.v1Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\xaa\x02\x18\x45stafette.CI.Manifest.V1b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_ESTAFETTESTAGE_ENVVARSENTRY = _descriptor.Descriptor(
  name='EnvVarsEntry',
  full_name='manifest.v1.EstafetteStage.EnvVarsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='manifest.v1.EstafetteStage.EnvVarsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='manifest.v1.EstafetteStage.EnvVarsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=433,
)

_ESTAFETTESTAGE_CUSTOMPROPERTIESENTRY = _descriptor.Descriptor(
  name='CustomPropertiesEntry',
  full_name='manifest.v1.EstafetteStage.CustomPropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='manifest.v1.EstafetteStage.CustomPropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='manifest.v1.EstafetteStage.CustomPropertiesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=512,
)

_ESTAFETTESTAGE = _descriptor.Descriptor(
  name='EstafetteStage',
  full_name='manifest.v1.EstafetteStage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='manifest.v1.EstafetteStage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='container_image', full_name='manifest.v1.EstafetteStage.container_image', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shell', full_name='manifest.v1.EstafetteStage.shell', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='working_directory', full_name='manifest.v1.EstafetteStage.working_directory', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commands', full_name='manifest.v1.EstafetteStage.commands', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='when', full_name='manifest.v1.EstafetteStage.when', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env_vars', full_name='manifest.v1.EstafetteStage.env_vars', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auto_injected', full_name='manifest.v1.EstafetteStage.auto_injected', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retries', full_name='manifest.v1.EstafetteStage.retries', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_properties', full_name='manifest.v1.EstafetteStage.custom_properties', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ESTAFETTESTAGE_ENVVARSENTRY, _ESTAFETTESTAGE_CUSTOMPROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=512,
)

_ESTAFETTESTAGE_ENVVARSENTRY.containing_type = _ESTAFETTESTAGE
_ESTAFETTESTAGE_CUSTOMPROPERTIESENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ESTAFETTESTAGE_CUSTOMPROPERTIESENTRY.containing_type = _ESTAFETTESTAGE
_ESTAFETTESTAGE.fields_by_name['env_vars'].message_type = _ESTAFETTESTAGE_ENVVARSENTRY
_ESTAFETTESTAGE.fields_by_name['custom_properties'].message_type = _ESTAFETTESTAGE_CUSTOMPROPERTIESENTRY
DESCRIPTOR.message_types_by_name['EstafetteStage'] = _ESTAFETTESTAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstafetteStage = _reflection.GeneratedProtocolMessageType('EstafetteStage', (_message.Message,), dict(

  EnvVarsEntry = _reflection.GeneratedProtocolMessageType('EnvVarsEntry', (_message.Message,), dict(
    DESCRIPTOR = _ESTAFETTESTAGE_ENVVARSENTRY,
    __module__ = 'manifest.v1.estafette_stage_pb2'
    # @@protoc_insertion_point(class_scope:manifest.v1.EstafetteStage.EnvVarsEntry)
    ))
  ,

  CustomPropertiesEntry = _reflection.GeneratedProtocolMessageType('CustomPropertiesEntry', (_message.Message,), dict(
    DESCRIPTOR = _ESTAFETTESTAGE_CUSTOMPROPERTIESENTRY,
    __module__ = 'manifest.v1.estafette_stage_pb2'
    # @@protoc_insertion_point(class_scope:manifest.v1.EstafetteStage.CustomPropertiesEntry)
    ))
  ,
  DESCRIPTOR = _ESTAFETTESTAGE,
  __module__ = 'manifest.v1.estafette_stage_pb2'
  # @@protoc_insertion_point(class_scope:manifest.v1.EstafetteStage)
  ))
_sym_db.RegisterMessage(EstafetteStage)
_sym_db.RegisterMessage(EstafetteStage.EnvVarsEntry)
_sym_db.RegisterMessage(EstafetteStage.CustomPropertiesEntry)


DESCRIPTOR._options = None
_ESTAFETTESTAGE_ENVVARSENTRY._options = None
_ESTAFETTESTAGE_CUSTOMPROPERTIESENTRY._options = None
# @@protoc_insertion_point(module_scope)
