# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.v1/estafette_release.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from manifest.v1 import estafette_release_action_pb2 as manifest_dot_v1_dot_estafette__release__action__pb2
from manifest.v1 import estafette_stage_pb2 as manifest_dot_v1_dot_estafette__stage__pb2
from manifest.v1 import estafette_trigger_pb2 as manifest_dot_v1_dot_estafette__trigger__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='manifest.v1/estafette_release.proto',
  package='manifest.v1',
  syntax='proto3',
  serialized_options=_b('\n\"io.estafette.ci.protos.manifest.v1Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\252\002\030Estafette.CI.Manifest.V1'),
  serialized_pb=_b('\n#manifest.v1/estafette_release.proto\x12\x0bmanifest.v1\x1a*manifest.v1/estafette_release_action.proto\x1a!manifest.v1/estafette_stage.proto\x1a#manifest.v1/estafette_trigger.proto\"\xce\x01\n\x10\x45stafetteRelease\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10\x63lone_repository\x18\x02 \x01(\x08\x12\x34\n\x07\x61\x63tions\x18\x03 \x03(\x0b\x32#.manifest.v1.EstafetteReleaseAction\x12/\n\x08triggers\x18\x04 \x03(\x0b\x32\x1d.manifest.v1.EstafetteTrigger\x12+\n\x06stages\x18\x05 \x03(\x0b\x32\x1b.manifest.v1.EstafetteStageB|\n\"io.estafette.ci.protos.manifest.v1Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\xaa\x02\x18\x45stafette.CI.Manifest.V1b\x06proto3')
  ,
  dependencies=[manifest_dot_v1_dot_estafette__release__action__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__stage__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__trigger__pb2.DESCRIPTOR,])




_ESTAFETTERELEASE = _descriptor.Descriptor(
  name='EstafetteRelease',
  full_name='manifest.v1.EstafetteRelease',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='manifest.v1.EstafetteRelease.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clone_repository', full_name='manifest.v1.EstafetteRelease.clone_repository', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='manifest.v1.EstafetteRelease.actions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggers', full_name='manifest.v1.EstafetteRelease.triggers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stages', full_name='manifest.v1.EstafetteRelease.stages', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=375,
)

_ESTAFETTERELEASE.fields_by_name['actions'].message_type = manifest_dot_v1_dot_estafette__release__action__pb2._ESTAFETTERELEASEACTION
_ESTAFETTERELEASE.fields_by_name['triggers'].message_type = manifest_dot_v1_dot_estafette__trigger__pb2._ESTAFETTETRIGGER
_ESTAFETTERELEASE.fields_by_name['stages'].message_type = manifest_dot_v1_dot_estafette__stage__pb2._ESTAFETTESTAGE
DESCRIPTOR.message_types_by_name['EstafetteRelease'] = _ESTAFETTERELEASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstafetteRelease = _reflection.GeneratedProtocolMessageType('EstafetteRelease', (_message.Message,), dict(
  DESCRIPTOR = _ESTAFETTERELEASE,
  __module__ = 'manifest.v1.estafette_release_pb2'
  # @@protoc_insertion_point(class_scope:manifest.v1.EstafetteRelease)
  ))
_sym_db.RegisterMessage(EstafetteRelease)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
