# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.v1/estafette_trigger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from manifest.v1 import estafette_pipeline_trigger_pb2 as manifest_dot_v1_dot_estafette__pipeline__trigger__pb2
from manifest.v1 import estafette_release_trigger_pb2 as manifest_dot_v1_dot_estafette__release__trigger__pb2
from manifest.v1 import estafette_git_trigger_pb2 as manifest_dot_v1_dot_estafette__git__trigger__pb2
from manifest.v1 import estafette_docker_trigger_pb2 as manifest_dot_v1_dot_estafette__docker__trigger__pb2
from manifest.v1 import estafette_cron_trigger_pb2 as manifest_dot_v1_dot_estafette__cron__trigger__pb2
from manifest.v1 import estafette_pub_sub_trigger_pb2 as manifest_dot_v1_dot_estafette__pub__sub__trigger__pb2
from manifest.v1 import estafette_trigger_build_action_pb2 as manifest_dot_v1_dot_estafette__trigger__build__action__pb2
from manifest.v1 import estafette_trigger_release_action_pb2 as manifest_dot_v1_dot_estafette__trigger__release__action__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='manifest.v1/estafette_trigger.proto',
  package='manifest.v1',
  syntax='proto3',
  serialized_options=_b('Z>github.com/estafette/estafette-ci-contracts-golang/manifest_v1'),
  serialized_pb=_b('\n#manifest.v1/estafette_trigger.proto\x12\x0bmanifest.v1\x1a,manifest.v1/estafette_pipeline_trigger.proto\x1a+manifest.v1/estafette_release_trigger.proto\x1a\'manifest.v1/estafette_git_trigger.proto\x1a*manifest.v1/estafette_docker_trigger.proto\x1a(manifest.v1/estafette_cron_trigger.proto\x1a+manifest.v1/estafette_pub_sub_trigger.proto\x1a\x30manifest.v1/estafette_trigger_build_action.proto\x1a\x32manifest.v1/estafette_trigger_release_action.proto\"\xd1\x03\n\x10\x45stafetteTrigger\x12\x37\n\x08pipeline\x18\x01 \x01(\x0b\x32%.manifest.v1.EstafettePipelineTrigger\x12\x35\n\x07release\x18\x02 \x01(\x0b\x32$.manifest.v1.EstafetteReleaseTrigger\x12-\n\x03git\x18\x03 \x01(\x0b\x32 .manifest.v1.EstafetteGitTrigger\x12\x33\n\x06\x64ocker\x18\x04 \x01(\x0b\x32#.manifest.v1.EstafetteDockerTrigger\x12/\n\x04\x63ron\x18\x05 \x01(\x0b\x32!.manifest.v1.EstafetteCronTrigger\x12\x34\n\x07pub_sub\x18\x06 \x01(\x0b\x32#.manifest.v1.EstafettePubSubTrigger\x12>\n\x0c\x62uild_action\x18\x07 \x01(\x0b\x32(.manifest.v1.EstafetteTriggerBuildAction\x12\x42\n\x0erelease_action\x18\x08 \x01(\x0b\x32*.manifest.v1.EstafetteTriggerReleaseActionB@Z>github.com/estafette/estafette-ci-contracts-golang/manifest_v1b\x06proto3')
  ,
  dependencies=[manifest_dot_v1_dot_estafette__pipeline__trigger__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__release__trigger__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__git__trigger__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__docker__trigger__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__cron__trigger__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__pub__sub__trigger__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__trigger__build__action__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__trigger__release__action__pb2.DESCRIPTOR,])




_ESTAFETTETRIGGER = _descriptor.Descriptor(
  name='EstafetteTrigger',
  full_name='manifest.v1.EstafetteTrigger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline', full_name='manifest.v1.EstafetteTrigger.pipeline', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='release', full_name='manifest.v1.EstafetteTrigger.release', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git', full_name='manifest.v1.EstafetteTrigger.git', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='docker', full_name='manifest.v1.EstafetteTrigger.docker', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cron', full_name='manifest.v1.EstafetteTrigger.cron', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pub_sub', full_name='manifest.v1.EstafetteTrigger.pub_sub', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_action', full_name='manifest.v1.EstafetteTrigger.build_action', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='release_action', full_name='manifest.v1.EstafetteTrigger.release_action', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=883,
)

_ESTAFETTETRIGGER.fields_by_name['pipeline'].message_type = manifest_dot_v1_dot_estafette__pipeline__trigger__pb2._ESTAFETTEPIPELINETRIGGER
_ESTAFETTETRIGGER.fields_by_name['release'].message_type = manifest_dot_v1_dot_estafette__release__trigger__pb2._ESTAFETTERELEASETRIGGER
_ESTAFETTETRIGGER.fields_by_name['git'].message_type = manifest_dot_v1_dot_estafette__git__trigger__pb2._ESTAFETTEGITTRIGGER
_ESTAFETTETRIGGER.fields_by_name['docker'].message_type = manifest_dot_v1_dot_estafette__docker__trigger__pb2._ESTAFETTEDOCKERTRIGGER
_ESTAFETTETRIGGER.fields_by_name['cron'].message_type = manifest_dot_v1_dot_estafette__cron__trigger__pb2._ESTAFETTECRONTRIGGER
_ESTAFETTETRIGGER.fields_by_name['pub_sub'].message_type = manifest_dot_v1_dot_estafette__pub__sub__trigger__pb2._ESTAFETTEPUBSUBTRIGGER
_ESTAFETTETRIGGER.fields_by_name['build_action'].message_type = manifest_dot_v1_dot_estafette__trigger__build__action__pb2._ESTAFETTETRIGGERBUILDACTION
_ESTAFETTETRIGGER.fields_by_name['release_action'].message_type = manifest_dot_v1_dot_estafette__trigger__release__action__pb2._ESTAFETTETRIGGERRELEASEACTION
DESCRIPTOR.message_types_by_name['EstafetteTrigger'] = _ESTAFETTETRIGGER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstafetteTrigger = _reflection.GeneratedProtocolMessageType('EstafetteTrigger', (_message.Message,), dict(
  DESCRIPTOR = _ESTAFETTETRIGGER,
  __module__ = 'manifest.v1.estafette_trigger_pb2'
  # @@protoc_insertion_point(class_scope:manifest.v1.EstafetteTrigger)
  ))
_sym_db.RegisterMessage(EstafetteTrigger)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
