# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/builder_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contracts.v1 import build_params_config_pb2 as contracts_dot_v1_dot_build__params__config__pb2
from contracts.v1 import build_version_config_pb2 as contracts_dot_v1_dot_build__version__config__pb2
from contracts.v1 import ci_server_config_pb2 as contracts_dot_v1_dot_ci__server__config__pb2
from contracts.v1 import credential_config_pb2 as contracts_dot_v1_dot_credential__config__pb2
from contracts.v1 import git_config_pb2 as contracts_dot_v1_dot_git__config__pb2
from contracts.v1 import release_params_config_pb2 as contracts_dot_v1_dot_release__params__config__pb2
from contracts.v1 import trusted_image_config_pb2 as contracts_dot_v1_dot_trusted__image__config__pb2
from manifest.v1 import estafette_event_pb2 as manifest_dot_v1_dot_estafette__event__pb2
from manifest.v1 import estafette_manifest_pb2 as manifest_dot_v1_dot_estafette__manifest__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contracts.v1/builder_config.proto',
  package='contracts.v1',
  syntax='proto3',
  serialized_options=_b('Z?github.com/estafette/estafette-ci-contracts-golang/contracts_v1\252\002\031Estafette.CI.Contracts.V1'),
  serialized_pb=_b('\n!contracts.v1/builder_config.proto\x12\x0c\x63ontracts.v1\x1a&contracts.v1/build_params_config.proto\x1a\'contracts.v1/build_version_config.proto\x1a#contracts.v1/ci_server_config.proto\x1a$contracts.v1/credential_config.proto\x1a\x1d\x63ontracts.v1/git_config.proto\x1a(contracts.v1/release_params_config.proto\x1a\'contracts.v1/trusted_image_config.proto\x1a!manifest.v1/estafette_event.proto\x1a$manifest.v1/estafette_manifest.proto\"\xda\x04\n\rBuilderConfig\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05track\x18\x02 \x01(\t\x12\x17\n\x0fregistry_mirror\x18\x03 \x01(\t\x12\x19\n\x11\x64ocker_daemon_mtu\x18\x04 \x01(\t\x12\x30\n\x08manifest\x18\x05 \x01(\x0b\x32\x1e.manifest.v1.EstafetteManifest\x12\x10\n\x08job_name\x18\x06 \x01(\t\x12\x14\n\x0crelease_name\x18\x07 \x01(\t\x12+\n\x06\x65vents\x18\x08 \x03(\x0b\x32\x1b.manifest.v1.EstafetteEvent\x12/\n\tci_server\x18\t \x01(\x0b\x32\x1c.contracts.v1.CIServerConfig\x12\x35\n\x0c\x62uild_params\x18\n \x01(\x0b\x32\x1f.contracts.v1.BuildParamsConfig\x12\x39\n\x0erelease_params\x18\x0b \x01(\x0b\x32!.contracts.v1.ReleaseParamsConfig\x12$\n\x03git\x18\x0c \x01(\x0b\x32\x17.contracts.v1.GitConfig\x12\x37\n\rbuild_version\x18\r \x01(\x0b\x32 .contracts.v1.BuildVersionConfig\x12\x33\n\x0b\x63redentials\x18\x0e \x03(\x0b\x32\x1e.contracts.v1.CredentialConfig\x12\x38\n\x0etrusted_images\x18\x0f \x03(\x0b\x32 .contracts.v1.TrustedImageConfigB]Z?github.com/estafette/estafette-ci-contracts-golang/contracts_v1\xaa\x02\x19\x45stafette.CI.Contracts.V1b\x06proto3')
  ,
  dependencies=[contracts_dot_v1_dot_build__params__config__pb2.DESCRIPTOR,contracts_dot_v1_dot_build__version__config__pb2.DESCRIPTOR,contracts_dot_v1_dot_ci__server__config__pb2.DESCRIPTOR,contracts_dot_v1_dot_credential__config__pb2.DESCRIPTOR,contracts_dot_v1_dot_git__config__pb2.DESCRIPTOR,contracts_dot_v1_dot_release__params__config__pb2.DESCRIPTOR,contracts_dot_v1_dot_trusted__image__config__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__event__pb2.DESCRIPTOR,manifest_dot_v1_dot_estafette__manifest__pb2.DESCRIPTOR,])




_BUILDERCONFIG = _descriptor.Descriptor(
  name='BuilderConfig',
  full_name='contracts.v1.BuilderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='contracts.v1.BuilderConfig.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track', full_name='contracts.v1.BuilderConfig.track', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='registry_mirror', full_name='contracts.v1.BuilderConfig.registry_mirror', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='docker_daemon_mtu', full_name='contracts.v1.BuilderConfig.docker_daemon_mtu', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manifest', full_name='contracts.v1.BuilderConfig.manifest', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job_name', full_name='contracts.v1.BuilderConfig.job_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='release_name', full_name='contracts.v1.BuilderConfig.release_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='contracts.v1.BuilderConfig.events', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ci_server', full_name='contracts.v1.BuilderConfig.ci_server', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_params', full_name='contracts.v1.BuilderConfig.build_params', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='release_params', full_name='contracts.v1.BuilderConfig.release_params', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git', full_name='contracts.v1.BuilderConfig.git', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_version', full_name='contracts.v1.BuilderConfig.build_version', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='credentials', full_name='contracts.v1.BuilderConfig.credentials', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trusted_images', full_name='contracts.v1.BuilderConfig.trusted_images', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=997,
)

_BUILDERCONFIG.fields_by_name['manifest'].message_type = manifest_dot_v1_dot_estafette__manifest__pb2._ESTAFETTEMANIFEST
_BUILDERCONFIG.fields_by_name['events'].message_type = manifest_dot_v1_dot_estafette__event__pb2._ESTAFETTEEVENT
_BUILDERCONFIG.fields_by_name['ci_server'].message_type = contracts_dot_v1_dot_ci__server__config__pb2._CISERVERCONFIG
_BUILDERCONFIG.fields_by_name['build_params'].message_type = contracts_dot_v1_dot_build__params__config__pb2._BUILDPARAMSCONFIG
_BUILDERCONFIG.fields_by_name['release_params'].message_type = contracts_dot_v1_dot_release__params__config__pb2._RELEASEPARAMSCONFIG
_BUILDERCONFIG.fields_by_name['git'].message_type = contracts_dot_v1_dot_git__config__pb2._GITCONFIG
_BUILDERCONFIG.fields_by_name['build_version'].message_type = contracts_dot_v1_dot_build__version__config__pb2._BUILDVERSIONCONFIG
_BUILDERCONFIG.fields_by_name['credentials'].message_type = contracts_dot_v1_dot_credential__config__pb2._CREDENTIALCONFIG
_BUILDERCONFIG.fields_by_name['trusted_images'].message_type = contracts_dot_v1_dot_trusted__image__config__pb2._TRUSTEDIMAGECONFIG
DESCRIPTOR.message_types_by_name['BuilderConfig'] = _BUILDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuilderConfig = _reflection.GeneratedProtocolMessageType('BuilderConfig', (_message.Message,), dict(
  DESCRIPTOR = _BUILDERCONFIG,
  __module__ = 'contracts.v1.builder_config_pb2'
  # @@protoc_insertion_point(class_scope:contracts.v1.BuilderConfig)
  ))
_sym_db.RegisterMessage(BuilderConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
