# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/build_params_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contracts.v1/build_params_config.proto',
  package='contracts.v1',
  syntax='proto3',
  serialized_options=_b('\n#io.estafette.ci.protos.contracts.v1Z<github.com/estafette/estafette-ci-protos-golang/contracts_v1\252\002\031Estafette.CI.Contracts.V1'),
  serialized_pb=_b('\n&contracts.v1/build_params_config.proto\x12\x0c\x63ontracts.v1\"%\n\x11\x42uildParamsConfig\x12\x10\n\x08\x62uild_id\x18\x01 \x01(\x03\x42\x7f\n#io.estafette.ci.protos.contracts.v1Z<github.com/estafette/estafette-ci-protos-golang/contracts_v1\xaa\x02\x19\x45stafette.CI.Contracts.V1b\x06proto3')
)




_BUILDPARAMSCONFIG = _descriptor.Descriptor(
  name='BuildParamsConfig',
  full_name='contracts.v1.BuildParamsConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_id', full_name='contracts.v1.BuildParamsConfig.build_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['BuildParamsConfig'] = _BUILDPARAMSCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildParamsConfig = _reflection.GeneratedProtocolMessageType('BuildParamsConfig', (_message.Message,), dict(
  DESCRIPTOR = _BUILDPARAMSCONFIG,
  __module__ = 'contracts.v1.build_params_config_pb2'
  # @@protoc_insertion_point(class_scope:contracts.v1.BuildParamsConfig)
  ))
_sym_db.RegisterMessage(BuildParamsConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
