# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/ci_server_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contracts.v1/ci_server_config.proto',
  package='contracts.v1',
  syntax='proto3',
  serialized_options=_b('Z?github.com/estafette/estafette-ci-contracts-golang/contracts_v1'),
  serialized_pb=_b('\n#contracts.v1/ci_server_config.proto\x12\x0c\x63ontracts.v1\"f\n\x0e\x43IServerConfig\x12\x10\n\x08\x62\x61se_url\x18\x01 \x01(\t\x12\x1a\n\x12\x62uilder_events_url\x18\x02 \x01(\t\x12\x15\n\rpost_logs_url\x18\x03 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x04 \x01(\tBAZ?github.com/estafette/estafette-ci-contracts-golang/contracts_v1b\x06proto3')
)




_CISERVERCONFIG = _descriptor.Descriptor(
  name='CIServerConfig',
  full_name='contracts.v1.CIServerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_url', full_name='contracts.v1.CIServerConfig.base_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='builder_events_url', full_name='contracts.v1.CIServerConfig.builder_events_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_logs_url', full_name='contracts.v1.CIServerConfig.post_logs_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_key', full_name='contracts.v1.CIServerConfig.api_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['CIServerConfig'] = _CISERVERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CIServerConfig = _reflection.GeneratedProtocolMessageType('CIServerConfig', (_message.Message,), dict(
  DESCRIPTOR = _CISERVERCONFIG,
  __module__ = 'contracts.v1.ci_server_config_pb2'
  # @@protoc_insertion_point(class_scope:contracts.v1.CIServerConfig)
  ))
_sym_db.RegisterMessage(CIServerConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
