# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/credential_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contracts.v1/credential_config.proto',
  package='contracts.v1',
  syntax='proto3',
  serialized_options=_b('Z?github.com/estafette/estafette-ci-contracts-golang/contracts_v1\252\002\031Estafette.CI.Contracts.V1'),
  serialized_pb=_b('\n$contracts.v1/credential_config.proto\x12\x0c\x63ontracts.v1\x1a\x19google/protobuf/any.proto\"\xda\x01\n\x10\x43redentialConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12W\n\x15\x61\x64\x64itional_properties\x18\x03 \x03(\x0b\x32\x38.contracts.v1.CredentialConfig.AdditionalPropertiesEntry\x1aQ\n\x19\x41\x64\x64itionalPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x42]Z?github.com/estafette/estafette-ci-contracts-golang/contracts_v1\xaa\x02\x19\x45stafette.CI.Contracts.V1b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_CREDENTIALCONFIG_ADDITIONALPROPERTIESENTRY = _descriptor.Descriptor(
  name='AdditionalPropertiesEntry',
  full_name='contracts.v1.CredentialConfig.AdditionalPropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='contracts.v1.CredentialConfig.AdditionalPropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='contracts.v1.CredentialConfig.AdditionalPropertiesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=300,
)

_CREDENTIALCONFIG = _descriptor.Descriptor(
  name='CredentialConfig',
  full_name='contracts.v1.CredentialConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='contracts.v1.CredentialConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='contracts.v1.CredentialConfig.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additional_properties', full_name='contracts.v1.CredentialConfig.additional_properties', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CREDENTIALCONFIG_ADDITIONALPROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=300,
)

_CREDENTIALCONFIG_ADDITIONALPROPERTIESENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_CREDENTIALCONFIG_ADDITIONALPROPERTIESENTRY.containing_type = _CREDENTIALCONFIG
_CREDENTIALCONFIG.fields_by_name['additional_properties'].message_type = _CREDENTIALCONFIG_ADDITIONALPROPERTIESENTRY
DESCRIPTOR.message_types_by_name['CredentialConfig'] = _CREDENTIALCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CredentialConfig = _reflection.GeneratedProtocolMessageType('CredentialConfig', (_message.Message,), dict(

  AdditionalPropertiesEntry = _reflection.GeneratedProtocolMessageType('AdditionalPropertiesEntry', (_message.Message,), dict(
    DESCRIPTOR = _CREDENTIALCONFIG_ADDITIONALPROPERTIESENTRY,
    __module__ = 'contracts.v1.credential_config_pb2'
    # @@protoc_insertion_point(class_scope:contracts.v1.CredentialConfig.AdditionalPropertiesEntry)
    ))
  ,
  DESCRIPTOR = _CREDENTIALCONFIG,
  __module__ = 'contracts.v1.credential_config_pb2'
  # @@protoc_insertion_point(class_scope:contracts.v1.CredentialConfig)
  ))
_sym_db.RegisterMessage(CredentialConfig)
_sym_db.RegisterMessage(CredentialConfig.AdditionalPropertiesEntry)


DESCRIPTOR._options = None
_CREDENTIALCONFIG_ADDITIONALPROPERTIESENTRY._options = None
# @@protoc_insertion_point(module_scope)
