# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/list_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from estafette.ci.contracts.v1 import pagination_pb2 as estafette_dot_ci_dot_contracts_dot_v1_dot_pagination__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='estafette/ci/contracts/v1/list_response.proto',
  package='estafette.ci.contracts.v1',
  syntax='proto3',
  serialized_options=_b('\n\035com.estafette.ci.contracts.v1P\001Z<github.com/estafette/estafette-ci-protos-golang/contracts/v1\252\002\031Estafette.Ci.Contracts.V1'),
  serialized_pb=_b('\n-estafette/ci/contracts/v1/list_response.proto\x12\x19\x65stafette.ci.contracts.v1\x1a*estafette/ci/contracts/v1/pagination.proto\x1a\x19google/protobuf/any.proto\"n\n\x0cListResponse\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x39\n\npagination\x18\x02 \x01(\x0b\x32%.estafette.ci.contracts.v1.PaginationB{\n\x1d\x63om.estafette.ci.contracts.v1P\x01Z<github.com/estafette/estafette-ci-protos-golang/contracts/v1\xaa\x02\x19\x45stafette.Ci.Contracts.V1b\x06proto3')
  ,
  dependencies=[estafette_dot_ci_dot_contracts_dot_v1_dot_pagination__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_LISTRESPONSE = _descriptor.Descriptor(
  name='ListResponse',
  full_name='estafette.ci.contracts.v1.ListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='estafette.ci.contracts.v1.ListResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='estafette.ci.contracts.v1.ListResponse.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=257,
)

_LISTRESPONSE.fields_by_name['items'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_LISTRESPONSE.fields_by_name['pagination'].message_type = estafette_dot_ci_dot_contracts_dot_v1_dot_pagination__pb2._PAGINATION
DESCRIPTOR.message_types_by_name['ListResponse'] = _LISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'estafette.ci.contracts.v1.list_response_pb2'
  # @@protoc_insertion_point(class_scope:estafette.ci.contracts.v1.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
