# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/trusted_image_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='estafette/ci/contracts/v1/trusted_image_config.proto',
  package='estafette.ci.contracts.v1',
  syntax='proto3',
  serialized_options=_b('\n\035com.estafette.ci.contracts.v1P\001Z<github.com/estafette/estafette-ci-protos-golang/contracts/v1\252\002\031Estafette.Ci.Contracts.V1'),
  serialized_pb=_b('\n4estafette/ci/contracts/v1/trusted_image_config.proto\x12\x19\x65stafette.ci.contracts.v1\"\x8f\x01\n\x12TrustedImageConfig\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x16\n\x0erun_privileged\x18\x02 \x01(\x08\x12\x12\n\nrun_docker\x18\x03 \x01(\x08\x12\x16\n\x0e\x61llow_commands\x18\x04 \x01(\x08\x12!\n\x19injected_credential_types\x18\x05 \x03(\tB{\n\x1d\x63om.estafette.ci.contracts.v1P\x01Z<github.com/estafette/estafette-ci-protos-golang/contracts/v1\xaa\x02\x19\x45stafette.Ci.Contracts.V1b\x06proto3')
)




_TRUSTEDIMAGECONFIG = _descriptor.Descriptor(
  name='TrustedImageConfig',
  full_name='estafette.ci.contracts.v1.TrustedImageConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_path', full_name='estafette.ci.contracts.v1.TrustedImageConfig.image_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_privileged', full_name='estafette.ci.contracts.v1.TrustedImageConfig.run_privileged', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_docker', full_name='estafette.ci.contracts.v1.TrustedImageConfig.run_docker', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allow_commands', full_name='estafette.ci.contracts.v1.TrustedImageConfig.allow_commands', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='injected_credential_types', full_name='estafette.ci.contracts.v1.TrustedImageConfig.injected_credential_types', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=227,
)

DESCRIPTOR.message_types_by_name['TrustedImageConfig'] = _TRUSTEDIMAGECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrustedImageConfig = _reflection.GeneratedProtocolMessageType('TrustedImageConfig', (_message.Message,), {
  'DESCRIPTOR' : _TRUSTEDIMAGECONFIG,
  '__module__' : 'estafette.ci.contracts.v1.trusted_image_config_pb2'
  # @@protoc_insertion_point(class_scope:estafette.ci.contracts.v1.TrustedImageConfig)
  })
_sym_db.RegisterMessage(TrustedImageConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
