# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/build_log_line.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/contracts.v1/build_log_line.proto',
  package='contracts.v1',
  syntax='proto3',
  serialized_options=_b('\n#io.estafette.ci.protos.contracts.v1Z<github.com/estafette/estafette-ci-protos-golang/contracts_v1\252\002\031Estafette.CI.Contracts.V1'),
  serialized_pb=_b('\n(protos/contracts.v1/build_log_line.proto\x12\x0c\x63ontracts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n\x0c\x42uildLogLine\x12\x13\n\x0bline_number\x18\x01 \x01(\x03\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bstream_type\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\tB\x7f\n#io.estafette.ci.protos.contracts.v1Z<github.com/estafette/estafette-ci-protos-golang/contracts_v1\xaa\x02\x19\x45stafette.CI.Contracts.V1b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_BUILDLOGLINE = _descriptor.Descriptor(
  name='BuildLogLine',
  full_name='contracts.v1.BuildLogLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_number', full_name='contracts.v1.BuildLogLine.line_number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='contracts.v1.BuildLogLine.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_type', full_name='contracts.v1.BuildLogLine.stream_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='contracts.v1.BuildLogLine.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=208,
)

_BUILDLOGLINE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['BuildLogLine'] = _BUILDLOGLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildLogLine = _reflection.GeneratedProtocolMessageType('BuildLogLine', (_message.Message,), dict(
  DESCRIPTOR = _BUILDLOGLINE,
  __module__ = 'protos.contracts.v1.build_log_line_pb2'
  # @@protoc_insertion_point(class_scope:contracts.v1.BuildLogLine)
  ))
_sym_db.RegisterMessage(BuildLogLine)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
