# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_cron_trigger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/manifest.v1/estafette_cron_trigger.proto',
  package='manifest.v1',
  syntax='proto3',
  serialized_options=_b('\n\"io.estafette.ci.protos.manifest.v1Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\252\002\030Estafette.CI.Manifest.V1'),
  serialized_pb=_b('\n/protos/manifest.v1/estafette_cron_trigger.proto\x12\x0bmanifest.v1\"(\n\x14\x45stafetteCronTrigger\x12\x10\n\x08schedule\x18\x01 \x01(\tB|\n\"io.estafette.ci.protos.manifest.v1Z;github.com/estafette/estafette-ci-protos-golang/manifest_v1\xaa\x02\x18\x45stafette.CI.Manifest.V1b\x06proto3')
)




_ESTAFETTECRONTRIGGER = _descriptor.Descriptor(
  name='EstafetteCronTrigger',
  full_name='manifest.v1.EstafetteCronTrigger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schedule', full_name='manifest.v1.EstafetteCronTrigger.schedule', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['EstafetteCronTrigger'] = _ESTAFETTECRONTRIGGER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstafetteCronTrigger = _reflection.GeneratedProtocolMessageType('EstafetteCronTrigger', (_message.Message,), dict(
  DESCRIPTOR = _ESTAFETTECRONTRIGGER,
  __module__ = 'protos.manifest.v1.estafette_cron_trigger_pb2'
  # @@protoc_insertion_point(class_scope:manifest.v1.EstafetteCronTrigger)
  ))
_sym_db.RegisterMessage(EstafetteCronTrigger)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
